# Generated by Django 3.1.4 on 2020-12-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission', models.PositiveIntegerField()),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('entry_points', models.PositiveIntegerField()),
                ('reg_date', models.DateTimeField(verbose_name='registration date')),
            ],
        ),
    ]
