# Generated by Django 3.1.4 on 2020-12-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_auto_20201214_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='ICS', max_length=200),
            preserve_default=False,
        ),
    ]
